 #!/bin/bash

# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalseLong/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic01_iid_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalseLong/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic01_iid_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalseLong/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic01_iid_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30


######################## ALL
# # alpha = 0
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_ALL_AVAIL --sine_wave=False --var_q_clients=0. --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_ALL_AVAIL --sine_wave=False --var_q_clients=0. --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_ALL_AVAIL --sine_wave=False --var_q_clients=0. --loss_pool_size=15 --num_users=100

# # alpha = 0
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_ALL_AVAIL --sine_wave=False --var_q_clients=0. --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_ALL_AVAIL --sine_wave=False --var_q_clients=0. --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_ALL_AVAIL --sine_wave=False --var_q_clients=0. --loss_pool_size=15 --num_users=100

# # alpha = 0
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_ALL_AVAIL --sine_wave=False --var_q_clients=0. --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_ALL_AVAIL --sine_wave=False --var_q_clients=0. --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_ALL_AVAIL --sine_wave=False --var_q_clients=0. --loss_pool_size=15 --num_users=100


# ######################## 
# ########################  IID AVAIL MODEL aka waveFalse

# # alpha=0
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_LARGE_A --sine_wave=False --var_q_clients=0.7 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_LARGE_A --sine_wave=False --var_q_clients=0.7 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_LARGE_A --sine_wave=False --var_q_clients=0.7 --loss_pool_size=15 --num_users=100


# # alpha=0.5
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_LARGE_A --sine_wave=False --var_q_clients=0.7 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_LARGE_A --sine_wave=False --var_q_clients=0.7 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_LARGE_A --sine_wave=False --var_q_clients=0.7 --loss_pool_size=15 --num_users=100

# # alpha=1
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_LARGE_A --sine_wave=False --var_q_clients=0.7 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_LARGE_A --sine_wave=False --var_q_clients=0.7 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_LARGE_A --sine_wave=False --var_q_clients=0.7 --loss_pool_size=15 --num_users=100



# ######################## 
# ########################   INVERSE aka waveFalse

# # alpha=0
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_INVERSE_A --sine_wave=False --var_q_clients=56 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_INVERSE_A --sine_wave=False --var_q_clients=56 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_INVERSE_A --sine_wave=False --var_q_clients=34 --loss_pool_size=15 --num_users=100


# # alpha=0.5
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_INVERSE_A --sine_wave=False --var_q_clients=56 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_INVERSE_A --sine_wave=False --var_q_clients=56 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_INVERSE_A --sine_wave=False --var_q_clients=34 --loss_pool_size=15 --num_users=100

# # alpha=1
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_INVERSE_A --sine_wave=False --var_q_clients=56 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_INVERSE_A --sine_wave=False --var_q_clients=56 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_INVERSE_A --sine_wave=False --var_q_clients=34 --loss_pool_size=15 --num_users=100


# ######################## 
# ########################   SMALL_A

# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --loss_pool_size=15


# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --loss_pool_size=15


# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_SMALL_A --sine_wave=False --var_q_clients=0.2 --num_users=100 --loss_pool_size=15


# ######################## 
# ########################  WAVE

# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_WAVE --sine_wave=True --var_q_clients=0.25 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_WAVE --sine_wave=True --var_q_clients=.25 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_WAVE --sine_wave=True --var_q_clients=0.25 --loss_pool_size=15 --num_users=100

# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_WAVE --sine_wave=True --var_q_clients=0.25 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_WAVE --sine_wave=True --var_q_clients=.25 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_WAVE --sine_wave=True --var_q_clients=0.25 --loss_pool_size=15 --num_users=100

# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_WAVE --sine_wave=True --var_q_clients=0.25 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/  --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_WAVE --sine_wave=True --var_q_clients=.25 --beta=0.001 --num_users=100
# bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_WAVE --sine_wave=True --var_q_clients=0.25 --loss_pool_size=15 --num_users=100


######################## 
########################   INDEP

bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_INDEP--sine_wave=False --var_q_clients=0.5 --num_users=100 --loss_pool_size=15


bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic55_fedavg_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100
bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic55_importance_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=0.5 --beta_data=0.5 --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic55_loss_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100 --loss_pool_size=15


bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100
bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/heterogeneity/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_INDEP --sine_wave=False --var_q_clients=0.5 --num_users=100 --loss_pool_size=15
