 #!/bin/bash

#all avail 
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/eminst_all_avail_models/ --schedule=none --experiment_name=emnist_fedavg_ALL_AVAIL --sine_wave=False --var_q_clients=0.
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=importance --beta=0.001--experiment_name=emnist_importance_ALL_AVAIL --sine_wave=False --var_q_clients=0. 
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=loss --experiment_name=emnist_loss_ALL_AVAIL --sine_wave=False --var_q_clients=0. --loss_pool_size=15

# small
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/eminst_all_avail_models/ --schedule=none --experiment_name=emnist_fedavg_SMALL_A --sine_wave=False --var_q_clients=0.2
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=importance --beta=0.001--experiment_name=emnist_importance_SMALL_A --sine_wave=False --var_q_clients=0.2 
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=loss --experiment_name=emnist_loss_SMALL_A --sine_wave=False --var_q_clients=0.2 --loss_pool_size=15

# inverse
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/eminst_all_avail_models/ --schedule=none --experiment_name=emnist_fedavg_INVERSE_A --sine_wave=False --var_q_clients=85
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=importance --beta=0.001--experiment_name=emnist_importance_INVERSE_A --sine_wave=False --var_q_clients=85 
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=loss --experiment_name=emnist_loss_INVERSE_A --sine_wave=False --var_q_clients=85 --loss_pool_size=15

# wave
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/eminst_all_avail_models/ --schedule=none --experiment_name=emnist_fedavg_WAVE --sine_wave=True --var_q_clients=0.25
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=importance --beta=0.001--experiment_name=emnist_importance_WAVE --sine_wave=True --var_q_clients=0.25
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=loss --experiment_name=emnist_loss_WAVE --sine_wave=True --var_q_clients=0.25 --loss_pool_size=15

# large
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/eminst_all_avail_models/ --schedule=none --experiment_name=emnist_fedavg_LARGE_A --sine_wave=False --var_q_clients=0.7
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=importance --beta=0.001--experiment_name=emnist_importance_LARGE_A --sine_wave=False --var_q_clients=0.7 
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --server_learning_rate=1. --root_output_dir=/home/monica/RESULTS/client_availability/emnist_all_avail_models/ --schedule=loss --experiment_name=emnist_loss_LARGE_A --sine_wave=False --var_q_clients=0.7 --loss_pool_size=15

