 #!/bin/bash

# inverse
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_INVERSE_A --sine_wave=False --var_q_clients=82
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=importance --server_learning_rate=3. --experiment_name=shakespeare_importance_INVERSE_A --sine_wave=False --var_q_clients=59 --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_INVERSE_A --sine_wave=False --var_q_clients=58 --loss_pool_size=15


# wave
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_WAVE --sine_wave=True --var_q_clients=.25
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=importance --server_learning_rate=3. --experiment_name=shakespeare_importance_WAVE --sine_wave=True --var_q_clients=.25 --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_WAVE --sine_wave=True --var_q_clients=.25 --loss_pool_size=15


#all avail 
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_ALL_AVAIL --sine_wave=False --var_q_clients=0.
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=importance --server_learning_rate=3. --experiment_name=shakespeare_importance_ALL_AVAIL --sine_wave=False --var_q_clients=0. --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_ALL_AVAIL --sine_wave=False --var_q_clients=0. --loss_pool_size=15

# small
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_SMALL_A --sine_wave=False --var_q_clients=0.2
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=importance --server_learning_rate=3. --experiment_name=shakespeare_importance_SMALL_A --sine_wave=False --var_q_clients=0.2 --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_SMALL_A --sine_wave=False --var_q_clients=0.2 --loss_pool_size=15

# large
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_LARGE_A --sine_wave=False --var_q_clients=.7
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=importance --server_learning_rate=3. --experiment_name=shakespeare_importance_LARGE_A --sine_wave=False --var_q_clients=.7 --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/shakespeare_all_avail_models/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_LARGE_A --sine_wave=False --var_q_clients=.7 --loss_pool_size=15
