 #!/bin/bash
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic01_iid_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic01_iid_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=1. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic01_iid_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=1. --beta_data=1. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30


bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_iid_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_iid_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=1 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_iid_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha=0. --beta_data=0. --iid=0 --total_rounds=200 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/syntheticWaveFalse/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

\