 #!/bin/bash

##########################
# FedAvg
##########################


# bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=none --server_learning_rate=3.162 --experiment_name=cifar_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=importance --beta=0.001 --server_learning_rate=3.162 --experiment_name=cifar_importance_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=loss --server_learning_rate=3.162 --experiment_name=cifar_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

# bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=none --server_learning_rate=1. --experiment_name=emnist_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=importance --server_learning_rate=1. --experiment_name=emnist_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
# bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=loss --server_learning_rate=1. --experiment_name=emnist_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

# bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

# bazel run main:federated_trainer -- --task=synthetic --alpha= 0. --beta_data=0. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic00_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=synthetic --alpha= 0. --beta_data=0. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic00_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
# bazel run main:federated_trainer -- --task=synthetic --alpha= 0. --beta_data=0. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic00_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30


# bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=none --server_learning_rate=1. --experiment_name=shakespeare_fedavg_waveFalse --sine_wave=False --var_q_clients=0.5
# bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=importance --server_learning_rate=1. --experiment_name=shakespeare_importance_waveFalse --sine_wave=False --var_q_clients=0.5 --beta=0.001
# bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=sgd  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/waveFalseFixedQ/ --schedule=loss --server_learning_rate=1. --experiment_name=shakespeare_loss_waveFalse --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

##########################
# FedAdam 
##########################

bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.0316228 --client_batch_size=20 --server_optimizer=adam  --server_adam_epsilon=0.1 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=none --server_learning_rate=1. --experiment_name=cifar_adam_INDEP --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.0316228 --client_batch_size=20 --server_optimizer=adam  --server_adam_epsilon=0.1 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=importance --beta=0.001 --server_learning_rate=3.162 --experiment_name=cifar_adam_importance_INDEP --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.0316228 --client_batch_size=20 --server_optimizer=adam  --server_adam_epsilon=0.1 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=loss --server_learning_rate=1. --experiment_name=cifar_adam_loss_INDEP --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30


bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=adam  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=none --server_learning_rate=1. --experiment_name=synthetic11_adam_INDEP --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=adam  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=importance --server_learning_rate=1. --experiment_name=synthetic11_adam_importance_INDEP --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=synthetic --alpha= 1. --beta_data=1. --iid=0 --total_rounds=1000 --client_optimizer=sgd --client_learning_rate=0.01 --client_batch_size=20 --server_optimizer=adam  --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=loss --server_learning_rate=1. --experiment_name=synthetic11_adam_loss_INDEP --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30


bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=adam  --server_adam_epsilon=0.001 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=none --server_learning_rate=0.01 --experiment_name=shakespeare_adam_INDEP --sine_wave=False --var_q_clients=0.5
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=adam  --server_adam_epsilon=0.001 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=importance --server_learning_rate=0.01 --experiment_name=shakespeare_adam_importance_INDEP --sine_wave=False --var_q_clients=0.5 --beta=0.001
bazel run main:federated_trainer -- --task=shakespeare --total_rounds=500 --client_optimizer=sgd --client_learning_rate=1. --client_batch_size=4 --server_optimizer=adam  --server_adam_epsilon=0.001 --clients_per_round=10 --client_epochs_per_round=1 --root_output_dir=/home/monica/RESULTS/client_availability/adam_independent_model/ --schedule=loss --server_learning_rate=0.01 --experiment_name=shakespeare_adam_loss_INDEP --sine_wave=False --var_q_clients=0.5 --loss_pool_size=30

